
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<div class="row">
    <div class="col">
        <div class="card" style="margin: 20px;">
            <div class="card-body">
                <h5 class="card-title">Capitulo 1: Controlando el flujo de un programa</h5>
                <h6 class="card-subtitle mb-2 text-muted">Tema 5: Implementar el manejo de exepciones</h6>
                <hr>
                <p class="card-text">
                    <h5>Relanzando una excepción</h5>
                    <ul>
                        <li>
                            Uno de los principios fundamentales del diseño de excepción es que detectar una excepción no debe conducir a que se oculten errores de otras partes de una
                            aplicación. A veces se detectará una excepción que debe "pasar" a un controlador de excepciones adjunto. Esto puede deberse a que el controlador de bajo
                            nivel no reconoce la excepción, o puede deberse a que un controlador de un nivel superior también debe ser alertado de la excepción que se produce. Se puede
                            volver a generar una excepción utilizando la palabra clave throw sin parámetro:
                            <pre>
throw;
</pre>
                        </li>
                        <li>
                            Puede pensar que al volver a lanzar una excepción, debe dar el objeto de excepción para que se vuelva a lanzar, como se muestra aquí:
                        </li>

                        <li>
                            Esta es una mala práctica porque eliminará la información de seguimiento de la pila que forma parte de la excepción original y la reemplazará con información
                            de seguimiento de la pila que describa la posición alcanzada en el código del controlador de excepciones. Esto hará que sea más difícil determinar qué sucede
                            cuando se produce el error, porque la ubicación del error se informará como en su controlador, en lugar de en el punto en el que se generó la excepción
                            original
                        </li>
                    </ul>
                    <h6> Excepciones internas</h6>
                    <ul>
                        <li>
                            Another way to manage the propagation of error conditions in an application is to pass the original exception object as an inner exception for a higher-level
                            exception handler to deal with. The Exception class contains an InnerException property that can be set when the exception is constructed. The constructor
                            for the newly created exception is given a reference to the original exception.
                        </li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>